//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int Account_id { get; set; }
        public string Account_name { get; set; }
        public string Pass { get; set; }
        public int Role_id { get; set; }
    }
}
