//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int Image_id { get; set; }
        public string Image_link { get; set; }
        public int Car_id { get; set; }
    
        public virtual car car { get; set; }
    }
}
